language: python
python:
  - "3.8"

before_install:
  - pip install --upgrade pip
  - pip install poetry

install: 
  - poetry install -v
  - npm install -g pyright

jobs:
  include:
    - stage: lint
      script: make lint
    - stage: test
      script: make test

after_success: codecov