language: python
python:
  - "3.8"
node_js:
  - 14

before_install:
  - pip install --upgrade pip
  - pip install poetry
  - npm i -g npm@latest

install: 
  - poetry install -v
  - npm -v
  - npm install -g pyright

jobs:
  include:
    - stage: lint
      script: make lint
    - stage: test
      script: make test

after_success: codecov