trigger:
- main

jobs:
- job: 'Linux'
  pool:
    vmImage: 'ubuntu-latest'

  strategy:
    matrix:
      Python38:
        python.version: '3.8'

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
        checkLatest: true
    
    - script: python -m pip install --upgrade pip poetry 
      displayName: 'Install poetry'

    - script: poetry install -v
      displayName: 'Install dependencies'
    
    - script: npm install -g pyright
      displayName: 'Install pyright'

    - script: make lint
      displayName: 'Lint'
  
    - script: make test
      displayName: 'Test'
    
    - script: poetry run coverage xml && poetry run coverage html
      displayName: 'Generating coverage files'
    
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'

    - task: PublishTestResults@2

      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '**/test-*.xml'
        testRunTitle: 'Publish test results for Python $(python.version)'
